### ISSUE TITLE
php-ast fails to build with php 8.5.0 alpha 1

### ISSUE THREAD

**Issue by wyattoday** [nikic/php-ast#251]
Attempting to build php 8.5.0 alpha 1 with php-ast fails with the following error:

```
/sources/php-8.5.0alpha1/ext/ast/ast_data.c:45:9: error: ‘ZEND_AST_CLONE’ undeclared here (not in a function); did you mean ‘ZEND_STR_CLONE’?
   45 |         ZEND_AST_CLONE,
      |         ^~~~~~~~~~~~~~
      |         ZEND_STR_CLONE
make: *** [Makefile:724: ext/ast/ast_data.lo] Error 1
```

`gcc --version`: `gcc (Debian 14.2.0-19) 14.2.0`
