### PR TITLE
Support PHP 8.4 property hooks in AST version 110

### LINKED ISSUE #240: Fails to compile with php 8.4.0 alpha 3 or newer
This extension (master branch) successfully compiled with php 8.4.0 alpha 2 and older, but now is failing with the newer builds:

```
ext\ast\ast.c(1518): error C2065: 'ZEND_DIM_ALTERNATIVE_SYNTAX': undeclared identifier
```

### PR DESCRIPTION
**Pull request by TysonAndre**
Add 'hooks' child of type `AST_PROPERTY_HOOK` to `AST_PROP_ELEM` and `AST_PARAM` (constructor property promotion).

Fixes #240

### CODE REVIEW

File: ast.c [hunk 1]
```diff
@@ -850,6 +870,19 @@ static void ast_fill_children_ht(HashTable *ht, zend_ast *ast, ast_state_info_t
...
 #endif
 
+#if PHP_VERSION_ID < 80400
+	if (state->version >= 110) {
+		if (ast_kind == ZEND_AST_PARAM || ast_kind == ZEND_AST_PROP_ELEM) {
+			zval tmp;
+			ZVAL_NULL(&tmp);
+			zend_hash_add_new(ht, AST_STR(str_hooks), &tmp);
+			/* For now, ast_kind_is_decl is false. */
+			/* TODO a future backwards incompatible release dropping support for older AST versions might have property elements as declarations? */
```
Comment (nikic) [inline ast.c:880]: I don't get this comment. ast_kind_is_decl() is determined by PHP, not this extension. It's about whether it uses zend_ast_decl.

File: ast.c [hunk 2]
```diff
@@ -1037,6 +1071,11 @@ static void ast_to_zval(zval *zv, zend_ast *ast, ast_state_info_t *state) {
 		// This is an undeclared dynamic property and has no cache slot.
 		ast_update_property_long(zv, AST_STR(str_endLineno), decl->end_lineno);
 
+#if PHP_VERSION_ID >= 80400
+		if (kind == ZEND_AST_CLOSURE || kind == ZEND_AST_ARROW_FUNC) {
+			ZVAL_STR(&tmp_zv, AST_STR(str_bracketed_closure));
```
Comment (nikic) [inline ast.c:1076]: What's this change for?

File: tests/php84_property_hook.phpt [hunk 3]
```diff
@@ -0,0 +1,58 @@
...
+                    0: AST_PROP_ELEM
+                        name: "prop"
+                        default: null
+                        docComment: null
+                        hooks: AST_STMT_LIST
+                            0: AST_PROPERTY_HOOK
+                                name: "get"
+                                docComment: null
+                                params: null
+                                uses: null
```
Comment (nikic) [inline tests/php84_property_hook.phpt:41]: I think we should hide unused nodes. E.g. use was dropped from AST_FUNC_DECL in version 60.

File: ast.c (hunk 2 above)
Comment (TysonAndre) [reply ast.c:1076]: It's because of https://github.com/php/php-src/pull/13550/files#diff-3e6742a9069b5717cf961c9d6b2aefbd1c730869d8a58123b1b5f3bc3e9082fc - php 8.4-dev has the name of closures be null instead of the old literal string `{closure}`.

This affects unit tests, but shouldn't really affect phan.

This could probably be extended to be consistently null in versions 110+ of php-ast.

File: ast.c (hunk 1 above)
Comment (TysonAndre) [reply ast.c:880]: Correct - I think I mixed up node kinds here, in retrospect - neither of those use `zend_ast_decl` - I was mixing those up with nodes that had reflection in general

File: tests/php84_property_hook.phpt (hunk 3 above)
Comment (TysonAndre) [reply tests/php84_property_hook.phpt]: Agreed, I forgot about that detail

File: ast.c (hunk 2 above)
Comment (TysonAndre) [reply ast.c:1079]: Or have the field be omitted entirely for closures and arrow functions.

File: README.md [hunk 4]
```diff
@@ -430,15 +430,17 @@ AST_NEW:                  class, args
...
 AST_POST_DEC:             var
 AST_POST_INC:             var
 AST_PRE_DEC:              var
 AST_PRE_INC:              var
 AST_PRINT:                expr
 AST_PROP:                 expr, prop
-AST_PROP_ELEM:            name, default, docComment
+AST_PROP_ELEM:            name, default, docComment, hooks // 'hooks' field added in version 110
 AST_PROP_GROUP:           type, props, attributes // version 70+
+AST_PROPERTY_HOOK:        name, docComment, params, stmts, returnType, attributes // version 110+
```
Comment (nikic) [inline README.md:442]: Drop returnType from here?

File: ast.c (hunk 2 above)
Comment (nikic) [reply ast.c:1079]: Probably omitting it entirely would be best. But we can leave that for a followup.

**Review by nikic — APPROVED** [review]
LGTM

**Review by nikic — APPROVED** [review]
