### ISSUE TITLE
Fails to compile with php 8.4.0 alpha 3 or newer

### ISSUE THREAD

**Issue by wyattoday** [nikic/php-ast#240]
This extension (master branch) successfully compiled with php 8.4.0 alpha 2 and older, but now is failing with the newer builds:

```
ext\ast\ast.c(1518): error C2065: 'ZEND_DIM_ALTERNATIVE_SYNTAX': undeclared identifier
```

**Comment by Jan-E** [comment]
ZEND_DIM_ALTERNATIVE_SYNTAX was removed by https://github.com/php/php-src/pull/14974
Compilation can be fixed by https://github.com/Jan-E/php-ast/commit/10b429406d3ac489967734ace27ef9122e0ffc6e
I did not run the tests yet.
@nikic Maybe further adjustments should be made. I merely fixed compilation on Windows with VS17.

**Comment by Jan-E** [comment]
@TysonAndre Thanks. I can confirm that version 110 compiles on Windows now.
